### ISSUE TITLE
Zoom out broken in 1.10.1

### ISSUE THREAD

**Issue by Solstice245** [azagaya/laigter#60] opened 2020-06-16 12:23 UTC
A second separate issue I had with 1.9.2 was the zoom out was not functional. I could only zoom in or reset the zoom level. This issue does not exist for me in 1.9.1.

**Comment by azagaya** [comment] 2020-06-16 12:46
Hi! could you tell me the operative system you are using?

**Comment by Solstice245** [comment] 2020-06-16 12:51
64bit machine with Windows 10.

**Comment by azagaya** [comment] 2020-06-16 13:40
I just tried in Windows 10 64 bit machine, and the zooms works fine in this pc. Both the wheel and the buttons in the toolbar. Perhaps someone else could reproduce this and help me.

**Comment by cassiussa** [comment] 2020-07-13 20:19
I get the same problem in version 1.10 as well. Can only zoom in, no zoom out.  Scroll wheel zooms in, regardless of the direction I scroll.

**Comment by azagaya** [comment] 2020-07-13 20:25
I just tested on MAC and it was working. IDK why i cannot reproduce this. I will continue investigating this. sorry for the inconveniences.
Does it also fails with touchpad?

**Comment by cassiussa** [comment] 2020-07-13 20:31
Yes, same issue with touchpad.  In fact, I just noticed that even the + and - icons only zoom as well.   So to recap, the +/- icons, touchpad, and scroll wheel on the mouse all only zoom in, regardless of which you choose.

**Comment by azagaya** [comment] 2020-07-13 20:33
Wow, that super strange, because i hardcoded positive and negative zoom to those buttons.

**Comment by cassiussa** [comment] 2020-07-13 20:37
I haven't been able to locate the relevant lines in code yet but am having a quick look.

**Comment by azagaya** [comment] 2020-07-13 20:41
[Here](https://github.com/azagaya/laigter/blob/master/src/open_gl_widget.cpp#L523) you have the code for the wheel @cassiussa

**Comment by azagaya** [comment] 2020-07-13 20:42
And [here](https://github.com/azagaya/laigter/blob/master/main_window.cpp#L677) for the toolbar buttons. If you help me debug this, it would be great!

**Comment by azagaya** [comment] 2020-07-13 20:44
May it be possible that for some systems, the wheel is reporting angle in x instead of y as expected?

**Comment by azagaya** [comment] 2020-07-13 20:53
Perhaps your mouse has too much definition? Im assuming 8 degrees on mouse movement because of Qt docs. But smaller resolution would cause that division always returning 0, thus you would zoom always in the same direction. I could try something like this. 
```c++
void MyWidget::wheelEvent(QWheelEvent *event)
{
    QPoint numPixels = event->pixelDelta();
    QPoint numDegrees = event->angleDelta() / 8;

    if (!numPixels.isNull()) {
        scrollWithPixels(numPixels);
    } else if (!numDegrees.isNull()) {
        QPoint numSteps = numDegrees / 15;
        scrollWithDegrees(numSteps);
    }

    event->accept();
}
```
would you be able to try if I try that change?

**Comment by cassiussa** [comment] 2020-07-13 20:53
Hmm, that's possible.  Yes, I can give it a try if you're able to perform a build?

**Comment by azagaya** [comment] 2020-07-13 20:54
Mac builds are done automatically, you can grab them on continuous tag in releases when done.. ill let you know. Give me some minutes.

**Comment by cassiussa** [comment] 2020-07-13 20:54
Oh wait.  But would that still explain why the icons also do the same?

**Comment by azagaya** [comment] 2020-07-13 20:55
No it wouldn't really. But i'm running out of ideas hehe, cause in the systems i tried, it works!

**Comment by cassiussa** [comment] 2020-07-13 20:59
The reproducibility curse!

**Comment by cassiussa** [comment] 2020-07-13 21:23
I gave it a whirl on the release from 17 minutes ago in Continuous tag.  Unfortunately the issue persists.  and I'm not really seeing anything in code that say "here's why" to me. :(

**Comment by azagaya** [comment] 2020-07-13 21:28
I need someone who can reproduce and debug this, cause everywhere i test, works fine... I'll mark this with help needed tag

**Comment by cassiussa** [comment] 2020-07-13 21:32
I'll see if I can get together some tools and run through some tests and debug.  c++ isn't a language I usually work in but can give it a shot.  Happen to know of a decent tool for OSX to compile this?  Have used this tool a bunch over the last 6 months or so and would definitely like to keep using it!

**Comment by azagaya** [comment] 2020-07-13 21:47
@cassiussa the best and easiest way to compile it would be using Qt Creator. You can see some vague instructions [here](https://github.com/azagaya/laigter#compiling-on-macos). The easiest way to install Qt Creator and all the framework is from qt online installer from qt.io (make sure to chose open source version). Sadly, since some months ago, for using Qt Creator and online installer you must register a free account, and thats a problem for many devs. You could compile it yourself, but its a hassle.
Im glad to hear you are being using laigter for that long! feel free to join us on discord and share your creations!

**Comment by azagaya** [comment] 2020-07-13 23:00
Maybe its the retina pixel ratio. Let me try something new.

**Comment by azagaya** [comment] 2020-07-13 23:24
@cassiussa would you try the build on continuos right now?

**Comment by cassiussa** [comment] 2020-07-14 00:18
@azagaya woohoo.  You got it!  I was also wondering if it was Retina but wasn't able to post here due to parental duties.  I can confirm that, at least on my Mac, scroll wheel, touchpad, and the +/- options all do what is expected.

Thanks so much for fixing that up.  Looking forward to trying a newer version than I currently run.

**Comment by azagaya** [comment] 2020-07-14 00:47
@cassiussa nice to hear it! it was logical now that i think. But that change can cause unexpected behaviours, so please tell me if you notice anything strange. Closing this for now, but feel free to reopen it.

**Comment by HeroicNate** [comment] 2020-09-16 05:58
Using the 1.10.1 portable build on windows I have the zoom issue downloading from itch and github.  Whether I use the mouse wheel or the UI button for zoom out, it always zooms in. 

After reading through this list of comments I tried it on another lower resolution monitor and the issue went away. It doesn't work properly on my 4k monitor.

**Comment by azagaya** [comment] 2020-09-16 12:39
ok! i'll reopen this And start looking for a solution.

**Comment by azagaya** [comment] 2020-09-27 15:39
@HeroicNate would you try the last release? [1.10.2](https://github.com/azagaya/laigter/releases/tag/1.10.2)

**Comment by azagaya** [comment] 2020-09-27 15:42
wait, ill have to reupload windows binaries

**Comment by azagaya** [comment] 2020-09-27 16:02
Now it should be there

**Comment by HeroicNate** [comment] 2020-09-27 19:02
That solved the zoom problem! It leaves a very small UI now but the functionality is working.
[Screen capture](https://cdn.discordapp.com/attachments/663542917540872215/759852171910447144/unknown.png)

**Comment by azagaya** [comment] 2020-09-27 19:35
Cool!

**Closed by azagaya** 2020-09-27 19:35 UTC
Labels: bug, help wanted
