### ISSUE TITLE
Make a new Mac Big Sur-specific icon for Laigter 

### ISSUE THREAD

**Issue by creepertron95** [azagaya/laigter#79] opened 2020-11-16 15:59 UTC
Not sure if it is important but, in the next MacOS version, The Laigter icon will probably look out of place on the new version. I feel a new Mac specific icon should be designed for this new version.

This is what the default MacOS Big Sur Icons are going to look like.
![](https://media.idownloadblog.com/wp-content/uploads/2020/06/macOS-Big-Sur-Control-Center.jpg)

Problem is, I only have Windows/Linux.

**Comment by Calinou** [comment] 2020-11-16 16:08
How many ISVs have designed specific macOS icons for Big Sur so far?

**Comment by creepertron95** [comment] 2020-11-16 16:15
Adobe has adapted their icons so far.

Visual Studio Code is considering it,
(https://github.com/microsoft/vscode/issues/101014)

and A (popular) website has sprung up providing Big Sur style icons for all of the applications that have not been changed yet. 
(https://macosicons.com/)

**Comment by azagaya** [comment] 2020-11-16 16:38
So the idea would be to add a rounded square as background to the icon, right? I think adding a specific icon won't be much trouble in Qt, so we may try.

**Comment by Calinou** [comment] 2020-11-16 16:39
It's probably a good idea to find a template for creating macOS Big Sur icons, since the background isn't a generic rounded rectangle, but rather a "squircle" which is difficult to reproduce by hand.

Unfortuantely, https://macosicons.com only has templates for proprietary editors, not open source software like Inkscape.

**Comment by creepertron95** [comment] 2020-11-17 04:35
![Laigter](https://user-images.githubusercontent.com/53346722/99347148-f3105180-285b-11eb-84ae-9788c24684c2.png)

**Comment by hazarek** [comment] 2020-11-17 05:50
also [IINA](https://github.com/iina/iina) has adapted their icons.

**Comment by Calinou** [comment] 2020-11-17 08:47
@hazarek I didn't refuse your suggestion (as in, I didn't close the proposal), I was just skeptical about whether we should do this.

However, if many third-party applications do this, it makes sense that we provide our own macOS Big Sur-friendly icon as well.

**Comment by hazarek** [comment] 2020-11-17 11:37
i will fix svg corners,  and share godot icns and template tonight

**Comment by creepertron95** [comment] 2020-11-17 12:46
Probably a good idea. (Turns out, both icons I submitted with the template got approved into the macOS Big Sur icon pack.) 
![mac-icons](https://user-images.githubusercontent.com/53346722/99391824-5f14a900-28a0-11eb-9f6d-78167301aea6.png)

**Comment by hazarek** [comment] 2020-11-17 12:47
@Calinou @creepertron95 
https://disk.yandex.com.tr/d/3F0t7EbRNOXvtw?w=1

**Comment by creepertron95** [comment] 2020-11-17 12:55
Using Modified BG.

![laigter-bigsur-fix](https://user-images.githubusercontent.com/53346722/99392757-db5bbc00-28a1-11eb-96a9-92901d886346.png)

**Comment by hazarek** [comment] 2020-11-17 13:24
@Calinou Big Sur pdf icon, It can be opened and edited easily with Vector editors;
https://yadi.sk/i/HXzyFUDuBHx4dA

 I'll post it as ICNS soon.

**Comment by azagaya** [comment] 2020-11-17 14:02
@creepertron95 i really like the icon! I will add to macos builds, and ask someone to test it on a mac. However.. should we only use the icon on Big Sur? Or should we just update it for all versions? Idk if we can use an icon per macos version.

**Comment by hazarek** [comment] 2020-11-17 14:05
@Calinou

<img width="251" alt="screenshot" src="https://user-images.githubusercontent.com/36481442/99399697-0e7c6a80-28f7-11eb-85a8-e8d5fcdb854a.png">

https://yadi.sk/d/krjMuny5KwToXQ
https://yadi.sk/d/3F0t7EbRNOXvtw?w=1

**Comment by creepertron95** [comment] 2020-11-17 14:37
@azagaya About that, this is what Apple has to say about it on their MacOS icon guidelines.

> 
> 
> IMPORTANT
When you update your app for macOS 11, use your new app icon design to replace the icon you designed for earlier versions. You can’t include two different app icons for one app, and the macOS 11 app icon style looks fine on a Mac running Catalina or earlier.

**Comment by hazarek** [comment] 2020-11-17 16:13
The grid on this page does not match the BigSur's icons. Not the same curve

https://developer.apple.com/design/human-interface-guidelines/macos/images/app-icon-layout-guides_2x.png

<img width="529" alt="test" src="https://user-images.githubusercontent.com/36481442/99415209-a040a380-2908-11eb-9d9e-c4c0afd1a5da.png">

**Comment by azagaya** [comment] 2020-11-17 16:22
@hazarek you mean that laigter's icon made by @creepertron95 doesn't match specification?

**Comment by creepertron95** [comment] 2020-11-17 16:33
I'll post link to source svg (Inkscape used) here. (https://github.com/creepertron95/Big-Sur-Icons-Custom/blob/main/laigter-bigsur-fix.png). @hazarek Does this mean all of the Big Sur icons (Including the ones at macosicons.com) are non-compliant?

**Comment by bruvzg** [comment] 2020-11-17 16:34
Official icon templates available at https://developer.apple.com/design/resources/#macos-apps (PSD variant is editable in Krita or GIMP).

**Comment by hazarek** [comment] 2020-11-17 16:56
> @hazarek you mean that laigter's icon made by @creepertron95 doesn't match specification?

no this png is wrong --> https://developer.apple.com/design/human-interface-guidelines/macos/images/app-icon-layout-guides_2x.png

these same and correct
https://yadi.sk/d/3F0t7EbRNOXvtw?w=1 and https://developer.apple.com/design/resources/#macos-apps

**Comment by creepertron95** [comment] 2020-11-17 16:58
The png seems correct, you just placed the icon at the outer bounding box, It's supposed to be at the icon grid bounding box referenced in the png.

**Comment by hazarek** [comment] 2020-11-17 17:03
> The png seems correct, you just placed the icon at the outer bounding box, It's supposed to be at the icon grid bounding box referenced in the png.

Ohh you are right.  my mistake. all of them are correct;

<img width="538" alt="asdasd" src="https://user-images.githubusercontent.com/36481442/99421872-e6e5cc00-290f-11eb-960d-76155633cb72.png">

**Comment by hazarek** [comment] 2020-11-17 17:09
> Official icon templates available at https://developer.apple.com/design/resources/#macos-apps (Photoshop variant is editable in Krita or GIMP).

Krita can't import  psd artboards

**Comment by azagaya** [comment] 2020-11-17 17:39
@creepertron95 so, the icon you made is ok, right?

**Comment by hazarek** [comment] 2020-11-17 17:41
> @creepertron95 so, the icon you made is ok, right?

yes but offical psd has better drop shadow. (official shadow)

**Comment by hazarek** [comment] 2020-11-17 17:55
big_sur_icon_template_1024.ora -> https://yadi.sk/d/uqj5W7hzcYpiEw

gimp and krita compatible

**Comment by azagaya** [comment] 2020-11-19 22:25
Now wee onnly need a macos user to try last continuous build.

**Comment by azagaya** [comment] 2020-12-03 12:06
I will close this, as the new icon is already in the master branch and was already tested by a mac user. I can reopen it if needed

**Closed by azagaya** 2020-12-03 12:06 UTC
