### ISSUE TITLE
App doesn't start on wayland

### ISSUE THREAD

**Issue by statisch** [azagaya/laigter#103] opened 2024-02-18 15:48 UTC
Attempting to run the AppImage prints out a few logs and exits with `QObject::disconnect: Unexpected nullptr parameter`.
And it seems to be a wayland issue:
`qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""`

OS: Ubuntu 22.04.3
GLSL: 4.60

**Comment by azagaya** [comment] 2024-02-19 14:19
Can you try run it with this please?

`QT_QPA_PLATFORM=xcb`

**Comment by statisch** [comment] 2024-02-19 15:22
Turns out it's not specifically a ubuntu/wayland issue but rather my wm, sway. Running the app on default gnome ubuntu works, but is far from perfect with glitching black screens that can only be fixed by resizing, checkboxes working in the opposite way for the tile x and tile y options etc.

**Comment by azagaya** [comment] 2024-02-19 17:33
Hey, I just tried on my Ubuntu 22.04.3 with Gnome and wayland, and i do not see any of those effects. Would you tell me what are your system specifications? Its very hard to know the issues without being able to reproduce.

**Comment by statisch** [comment] 2024-02-20 21:07
OS: Ubuntu 22.04.4 LTS x86_64
Kernel: 6.5.0-18-generic
DE: GNOME 42.9
GPU: RX6600 navi 23, amdgpu drivers

It seems to have updated recently to 24.04.4 for me, maybe that?

**Comment by azagaya** [comment] 2024-02-21 16:28
I will have to try. Im about to leave on a trip, so ill check it when im back.

**Comment by azagaya** [comment] 2024-10-11 17:38
I wont be able to publish on steam anytime soon, so i will close this issue... Maybe ill have a second thought in the future.

**Comment by azagaya** [comment] 2024-10-11 18:41
Just tested on Ubuntu 24.04 and works fine in my end. Ill close this as i cannot reproduce it, sorry.

**Closed** 2024-10-11 18:41 UTC
