### ISSUE TITLE
Preview Export Is Cropped

### ISSUE THREAD

**Issue by shtr86** [azagaya/laigter#81] opened 2021-02-20 09:59 UTC
Hi.

Looks like in the last version of software the preview export is bugged and crops the final result which the in the previous versions doesn't seem to exist.

No matter what the resolution of imported texture is. it only exports this area size (1402:937) (only happens when it's bigger than this size).

And finally, thank for all the efforts you put into this useful project.

OS: Windows 10 64bit
Laigter version: 1.10.3

**Comment by azagaya** [comment] 2021-02-20 12:55
Hi!
Thanks for reporting the issue... i think i know what could have happened... Would you share me the texture you are using?

**Comment by shtr86** [comment] 2021-02-20 13:43
of course ! There you go.

![icon google play game](https://user-images.githubusercontent.com/79358281/108597508-b09c6a80-739e-11eb-9672-0c954ae33de7.png)
![icon google play game_v](https://user-images.githubusercontent.com/79358281/108597516-b6924b80-739e-11eb-86de-b824e65177c5.png)

**Comment by azagaya** [comment] 2021-02-20 19:27
@shtr86 would you check if its working fine in the version 1.10.4 in releases?

**Comment by azagaya** [comment] 2021-02-22 19:56
@shtr86 would you confirm if the issue is solved in last release?

**Comment by shtr86** [comment] 2021-02-23 07:34
It works perfectly fine in version "1.10.5". Ty 👍 

I'm not sure if it's a right way to make an suggestion or not. But since I really like to use the baked version of my textures with your software. I noticed there is some changes done to my final result in preview exports. Here is an example

![Test](https://user-images.githubusercontent.com/79358281/108813276-f4bd8400-75c5-11eb-9669-1e9e9840c737.JPG)

As you can see the corners loose their smoothness and lose their alpha channel. I guess, maybe there is some calculation issue there. I would really appreciate if you fix this one too.

I would close this issue tomorrow anyways.
Thanks. :)

**Comment by azagaya** [comment] 2021-02-23 15:53
Oh.. thats probably because laigter export preview in premultiplied alpha format. Perhaps you could check if you have an premultiplied alpha import option in the software you are using?
If not, i can make that an option for next release perhaps.

**Comment by azagaya** [comment] 2021-02-23 17:39
I will close this for now, if you persist with that issue, feel free to open another issue! as that problem is unrelated to the original topic of this one.

**Closed by azagaya** 2021-02-23 17:39 UTC
